### ISSUE TITLE
Game runs/projectiles

### ISSUE THREAD

**Issue by ZataraTMM** [DinoDevs/Everwing-Hacks#13]
Sorry for spamming the "issues" with questions like these.

Would it be possible to fake a game run on score or disable projectiles  like boss bullets/meteors?

I've seen old methods of disabling the meteors but..they're old/patched.

**Comment by GramThanos** [comment]
Well most people were just caring about geting gold. I have such a hack... but... people will use it to score high on groups too. I don't want that.

For these reasons, I don't want to release such hacks public (damage hacks, score hack etc).

PS: there is no problem with issue spaming, that's why they exist.
